const countries =
{
   "Message": "",
   "Global": {
      "NewConfirmed": 262645,
      "TotalConfirmed": 31774394,
      "NewDeaths": 5562,
      "TotalDeaths": 975040,
      "NewRecovered": 265924,
      "TotalRecovered": 21886648
   },
   "Countries": [
      {
         "Country": "Afghanistan",
         "CountryCode": "AF",
         "Slug": "afghanistan",
         "NewConfirmed": 49,
         "TotalConfirmed": 39145,
         "NewDeaths": 1,
         "TotalDeaths": 1446,
         "NewRecovered": 34,
         "TotalRecovered": 32610,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Albania",
         "CountryCode": "AL",
         "Slug": "albania",
         "NewConfirmed": 121,
         "TotalConfirmed": 12787,
         "NewDeaths": 3,
         "TotalDeaths": 370,
         "NewRecovered": 97,
         "TotalRecovered": 7139,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Algeria",
         "CountryCode": "DZ",
         "Slug": "algeria",
         "NewConfirmed": 186,
         "TotalConfirmed": 50400,
         "NewDeaths": 9,
         "TotalDeaths": 1698,
         "NewRecovered": 121,
         "TotalRecovered": 35428,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Andorra",
         "CountryCode": "AD",
         "Slug": "andorra",
         "NewConfirmed": 72,
         "TotalConfirmed": 1753,
         "NewDeaths": 0,
         "TotalDeaths": 53,
         "NewRecovered": 4,
         "TotalRecovered": 1203,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Angola",
         "CountryCode": "AO",
         "Slug": "angola",
         "NewConfirmed": 127,
         "TotalConfirmed": 4363,
         "NewDeaths": 4,
         "TotalDeaths": 159,
         "NewRecovered": 11,
         "TotalRecovered": 1473,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Antigua and Barbuda",
         "CountryCode": "AG",
         "Slug": "antigua-and-barbuda",
         "NewConfirmed": 1,
         "TotalConfirmed": 97,
         "NewDeaths": 0,
         "TotalDeaths": 3,
         "NewRecovered": 0,
         "TotalRecovered": 92,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Argentina",
         "CountryCode": "AR",
         "Slug": "argentina",
         "NewConfirmed": 12625,
         "TotalConfirmed": 664799,
         "NewDeaths": 424,
         "TotalDeaths": 14376,
         "NewRecovered": 8258,
         "TotalRecovered": 525486,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Armenia",
         "CountryCode": "AM",
         "Slug": "armenia",
         "NewConfirmed": 210,
         "TotalConfirmed": 47877,
         "NewDeaths": 4,
         "TotalDeaths": 942,
         "NewRecovered": 350,
         "TotalRecovered": 43026,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Australia",
         "CountryCode": "AU",
         "Slug": "australia",
         "NewConfirmed": 8,
         "TotalConfirmed": 26980,
         "NewDeaths": 2,
         "TotalDeaths": 861,
         "NewRecovered": 117,
         "TotalRecovered": 24446,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Austria",
         "CountryCode": "AT",
         "Slug": "austria",
         "NewConfirmed": 681,
         "TotalConfirmed": 39984,
         "NewDeaths": 6,
         "TotalDeaths": 777,
         "NewRecovered": 637,
         "TotalRecovered": 30949,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Azerbaijan",
         "CountryCode": "AZ",
         "Slug": "azerbaijan",
         "NewConfirmed": 146,
         "TotalConfirmed": 39524,
         "NewDeaths": 2,
         "TotalDeaths": 580,
         "NewRecovered": 173,
         "TotalRecovered": 37122,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Bahamas",
         "CountryCode": "BS",
         "Slug": "bahamas",
         "NewConfirmed": 151,
         "TotalConfirmed": 3618,
         "NewDeaths": 3,
         "TotalDeaths": 80,
         "NewRecovered": 44,
         "TotalRecovered": 1915,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Bahrain",
         "CountryCode": "BH",
         "Slug": "bahrain",
         "NewConfirmed": 612,
         "TotalConfirmed": 67014,
         "NewDeaths": 4,
         "TotalDeaths": 231,
         "NewRecovered": 750,
         "TotalRecovered": 60117,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Bangladesh",
         "CountryCode": "BD",
         "Slug": "bangladesh",
         "NewConfirmed": 1666,
         "TotalConfirmed": 353844,
         "NewDeaths": 37,
         "TotalDeaths": 5044,
         "NewRecovered": 2163,
         "TotalRecovered": 262953,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Barbados",
         "CountryCode": "BB",
         "Slug": "barbados",
         "NewConfirmed": 0,
         "TotalConfirmed": 189,
         "NewDeaths": 0,
         "TotalDeaths": 7,
         "NewRecovered": 1,
         "TotalRecovered": 174,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Belarus",
         "CountryCode": "BY",
         "Slug": "belarus",
         "NewConfirmed": 253,
         "TotalConfirmed": 76357,
         "NewDeaths": 5,
         "TotalDeaths": 796,
         "NewRecovered": 178,
         "TotalRecovered": 73564,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Belgium",
         "CountryCode": "BE",
         "Slug": "belgium",
         "NewConfirmed": 1661,
         "TotalConfirmed": 106887,
         "NewDeaths": 4,
         "TotalDeaths": 9959,
         "NewRecovered": 40,
         "TotalRecovered": 19079,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Belize",
         "CountryCode": "BZ",
         "Slug": "belize",
         "NewConfirmed": 71,
         "TotalConfirmed": 1706,
         "NewDeaths": 1,
         "TotalDeaths": 22,
         "NewRecovered": 52,
         "TotalRecovered": 1019,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Benin",
         "CountryCode": "BJ",
         "Slug": "benin",
         "NewConfirmed": 31,
         "TotalConfirmed": 2325,
         "NewDeaths": 0,
         "TotalDeaths": 40,
         "NewRecovered": 0,
         "TotalRecovered": 1954,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Bhutan",
         "CountryCode": "BT",
         "Slug": "bhutan",
         "NewConfirmed": 0,
         "TotalConfirmed": 261,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 1,
         "TotalRecovered": 196,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Bolivia",
         "CountryCode": "BO",
         "Slug": "bolivia",
         "NewConfirmed": 537,
         "TotalConfirmed": 131990,
         "NewDeaths": 38,
         "TotalDeaths": 7731,
         "NewRecovered": 703,
         "TotalRecovered": 91556,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Bosnia and Herzegovina",
         "CountryCode": "BA",
         "Slug": "bosnia-and-herzegovina",
         "NewConfirmed": 344,
         "TotalConfirmed": 26081,
         "NewDeaths": 12,
         "TotalDeaths": 790,
         "NewRecovered": 275,
         "TotalRecovered": 18634,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Botswana",
         "CountryCode": "BW",
         "Slug": "botswana",
         "NewConfirmed": 0,
         "TotalConfirmed": 2567,
         "NewDeaths": 0,
         "TotalDeaths": 13,
         "NewRecovered": 0,
         "TotalRecovered": 624,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Brazil",
         "CountryCode": "BR",
         "Slug": "brazil",
         "NewConfirmed": 0,
         "TotalConfirmed": 4591364,
         "NewDeaths": 0,
         "TotalDeaths": 138105,
         "NewRecovered": 29996,
         "TotalRecovered": 4046827,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Brunei Darussalam",
         "CountryCode": "BN",
         "Slug": "brunei",
         "NewConfirmed": 0,
         "TotalConfirmed": 145,
         "NewDeaths": 0,
         "TotalDeaths": 3,
         "NewRecovered": 0,
         "TotalRecovered": 142,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Bulgaria",
         "CountryCode": "BG",
         "Slug": "bulgaria",
         "NewConfirmed": 160,
         "TotalConfirmed": 19283,
         "NewDeaths": 12,
         "TotalDeaths": 779,
         "NewRecovered": 119,
         "TotalRecovered": 13867,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Burkina Faso",
         "CountryCode": "BF",
         "Slug": "burkina-faso",
         "NewConfirmed": 22,
         "TotalConfirmed": 1929,
         "NewDeaths": 0,
         "TotalDeaths": 56,
         "NewRecovered": 0,
         "TotalRecovered": 1252,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Burundi",
         "CountryCode": "BI",
         "Slug": "burundi",
         "NewConfirmed": 2,
         "TotalConfirmed": 476,
         "NewDeaths": 0,
         "TotalDeaths": 1,
         "NewRecovered": 0,
         "TotalRecovered": 462,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Cambodia",
         "CountryCode": "KH",
         "Slug": "cambodia",
         "NewConfirmed": 0,
         "TotalConfirmed": 275,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 274,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Cameroon",
         "CountryCode": "CM",
         "Slug": "cameroon",
         "NewConfirmed": 92,
         "TotalConfirmed": 20690,
         "NewDeaths": 0,
         "TotalDeaths": 416,
         "NewRecovered": 0,
         "TotalRecovered": 19124,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Canada",
         "CountryCode": "CA",
         "Slug": "canada",
         "NewConfirmed": 1084,
         "TotalConfirmed": 149926,
         "NewDeaths": 8,
         "TotalDeaths": 9293,
         "NewRecovered": 960,
         "TotalRecovered": 129850,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Cape Verde",
         "CountryCode": "CV",
         "Slug": "cape-verde",
         "NewConfirmed": 75,
         "TotalConfirmed": 5412,
         "NewDeaths": 2,
         "TotalDeaths": 54,
         "NewRecovered": 95,
         "TotalRecovered": 4837,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Central African Republic",
         "CountryCode": "CF",
         "Slug": "central-african-republic",
         "NewConfirmed": 0,
         "TotalConfirmed": 4802,
         "NewDeaths": 0,
         "TotalDeaths": 62,
         "NewRecovered": 0,
         "TotalRecovered": 1830,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Chad",
         "CountryCode": "TD",
         "Slug": "chad",
         "NewConfirmed": 9,
         "TotalConfirmed": 1164,
         "NewDeaths": 1,
         "TotalDeaths": 82,
         "NewRecovered": 30,
         "TotalRecovered": 997,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Chile",
         "CountryCode": "CL",
         "Slug": "chile",
         "NewConfirmed": 1380,
         "TotalConfirmed": 449903,
         "NewDeaths": 24,
         "TotalDeaths": 12345,
         "NewRecovered": 1989,
         "TotalRecovered": 425165,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "China",
         "CountryCode": "CN",
         "Slug": "china",
         "NewConfirmed": 10,
         "TotalConfirmed": 90409,
         "NewDeaths": 1,
         "TotalDeaths": 4738,
         "NewRecovered": 29,
         "TotalRecovered": 85304,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Colombia",
         "CountryCode": "CO",
         "Slug": "colombia",
         "NewConfirmed": 6731,
         "TotalConfirmed": 784268,
         "NewDeaths": 349,
         "TotalDeaths": 24746,
         "NewRecovered": 21377,
         "TotalRecovered": 662277,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Comoros",
         "CountryCode": "KM",
         "Slug": "comoros",
         "NewConfirmed": 0,
         "TotalConfirmed": 470,
         "NewDeaths": 0,
         "TotalDeaths": 7,
         "NewRecovered": 0,
         "TotalRecovered": 453,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Congo (Brazzaville)",
         "CountryCode": "CG",
         "Slug": "congo-brazzaville",
         "NewConfirmed": 3,
         "TotalConfirmed": 5005,
         "NewDeaths": 0,
         "TotalDeaths": 89,
         "NewRecovered": 0,
         "TotalRecovered": 3887,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Congo (Kinshasa)",
         "CountryCode": "CD",
         "Slug": "congo-kinshasa",
         "NewConfirmed": 14,
         "TotalConfirmed": 10537,
         "NewDeaths": 0,
         "TotalDeaths": 271,
         "NewRecovered": 30,
         "TotalRecovered": 10041,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Costa Rica",
         "CountryCode": "CR",
         "Slug": "costa-rica",
         "NewConfirmed": 1370,
         "TotalConfirmed": 68059,
         "NewDeaths": 21,
         "TotalDeaths": 781,
         "NewRecovered": 430,
         "TotalRecovered": 26136,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Croatia",
         "CountryCode": "HR",
         "Slug": "croatia",
         "NewConfirmed": 204,
         "TotalConfirmed": 15340,
         "NewDeaths": 2,
         "TotalDeaths": 257,
         "NewRecovered": 828,
         "TotalRecovered": 13815,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Cuba",
         "CountryCode": "CU",
         "Slug": "cuba",
         "NewConfirmed": 48,
         "TotalConfirmed": 5270,
         "NewDeaths": 1,
         "TotalDeaths": 118,
         "NewRecovered": 76,
         "TotalRecovered": 4582,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Cyprus",
         "CountryCode": "CY",
         "Slug": "cyprus",
         "NewConfirmed": 36,
         "TotalConfirmed": 1654,
         "NewDeaths": 0,
         "TotalDeaths": 22,
         "NewRecovered": 0,
         "TotalRecovered": 1369,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Czech Republic",
         "CountryCode": "CZ",
         "Slug": "czech-republic",
         "NewConfirmed": 2306,
         "TotalConfirmed": 55464,
         "NewDeaths": 24,
         "TotalDeaths": 555,
         "NewRecovered": 558,
         "TotalRecovered": 26709,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Côte d'Ivoire",
         "CountryCode": "CI",
         "Slug": "cote-divoire",
         "NewConfirmed": 87,
         "TotalConfirmed": 19430,
         "NewDeaths": 0,
         "TotalDeaths": 120,
         "NewRecovered": 193,
         "TotalRecovered": 18875,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Denmark",
         "CountryCode": "DK",
         "Slug": "denmark",
         "NewConfirmed": 561,
         "TotalConfirmed": 24822,
         "NewDeaths": 2,
         "TotalDeaths": 643,
         "NewRecovered": 326,
         "TotalRecovered": 18789,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Djibouti",
         "CountryCode": "DJ",
         "Slug": "djibouti",
         "NewConfirmed": 0,
         "TotalConfirmed": 5407,
         "NewDeaths": 0,
         "TotalDeaths": 61,
         "NewRecovered": 0,
         "TotalRecovered": 5338,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Dominica",
         "CountryCode": "DM",
         "Slug": "dominica",
         "NewConfirmed": 0,
         "TotalConfirmed": 24,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 18,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Dominican Republic",
         "CountryCode": "DO",
         "Slug": "dominican-republic",
         "NewConfirmed": 468,
         "TotalConfirmed": 109737,
         "NewDeaths": 10,
         "TotalDeaths": 2074,
         "NewRecovered": 693,
         "TotalRecovered": 83434,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Ecuador",
         "CountryCode": "EC",
         "Slug": "ecuador",
         "NewConfirmed": 2249,
         "TotalConfirmed": 129892,
         "NewDeaths": 45,
         "TotalDeaths": 11171,
         "NewRecovered": 0,
         "TotalRecovered": 102852,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Egypt",
         "CountryCode": "EG",
         "Slug": "egypt",
         "NewConfirmed": 121,
         "TotalConfirmed": 102375,
         "NewDeaths": 16,
         "TotalDeaths": 5822,
         "NewRecovered": 700,
         "TotalRecovered": 91843,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "El Salvador",
         "CountryCode": "SV",
         "Slug": "el-salvador",
         "NewConfirmed": 0,
         "TotalConfirmed": 27954,
         "NewDeaths": 5,
         "TotalDeaths": 819,
         "NewRecovered": 0,
         "TotalRecovered": 22113,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Equatorial Guinea",
         "CountryCode": "GQ",
         "Slug": "equatorial-guinea",
         "NewConfirmed": 0,
         "TotalConfirmed": 5018,
         "NewDeaths": 0,
         "TotalDeaths": 83,
         "NewRecovered": 0,
         "TotalRecovered": 4509,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Eritrea",
         "CountryCode": "ER",
         "Slug": "eritrea",
         "NewConfirmed": 0,
         "TotalConfirmed": 364,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 309,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Estonia",
         "CountryCode": "EE",
         "Slug": "estonia",
         "NewConfirmed": 57,
         "TotalConfirmed": 3033,
         "NewDeaths": 0,
         "TotalDeaths": 64,
         "NewRecovered": 2,
         "TotalRecovered": 2387,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Ethiopia",
         "CountryCode": "ET",
         "Slug": "ethiopia",
         "NewConfirmed": 661,
         "TotalConfirmed": 71083,
         "NewDeaths": 14,
         "TotalDeaths": 1141,
         "NewRecovered": 262,
         "TotalRecovered": 29253,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Fiji",
         "CountryCode": "FJ",
         "Slug": "fiji",
         "NewConfirmed": 0,
         "TotalConfirmed": 32,
         "NewDeaths": 0,
         "TotalDeaths": 2,
         "NewRecovered": 0,
         "TotalRecovered": 28,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Finland",
         "CountryCode": "FI",
         "Slug": "finland",
         "NewConfirmed": 93,
         "TotalConfirmed": 9288,
         "NewDeaths": 2,
         "TotalDeaths": 343,
         "NewRecovered": 150,
         "TotalRecovered": 7850,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "France",
         "CountryCode": "FR",
         "Slug": "france",
         "NewConfirmed": 1306,
         "TotalConfirmed": 508456,
         "NewDeaths": 21,
         "TotalDeaths": 31447,
         "NewRecovered": 1537,
         "TotalRecovered": 96498,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Gabon",
         "CountryCode": "GA",
         "Slug": "gabon",
         "NewConfirmed": 12,
         "TotalConfirmed": 8716,
         "NewDeaths": 0,
         "TotalDeaths": 54,
         "NewRecovered": 31,
         "TotalRecovered": 7906,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Gambia",
         "CountryCode": "GM",
         "Slug": "gambia",
         "NewConfirmed": 2,
         "TotalConfirmed": 3542,
         "NewDeaths": 0,
         "TotalDeaths": 110,
         "NewRecovered": 9,
         "TotalRecovered": 2011,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Georgia",
         "CountryCode": "GE",
         "Slug": "georgia",
         "NewConfirmed": 227,
         "TotalConfirmed": 4140,
         "NewDeaths": 2,
         "TotalDeaths": 25,
         "NewRecovered": 69,
         "TotalRecovered": 1643,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Germany",
         "CountryCode": "DE",
         "Slug": "germany",
         "NewConfirmed": 1613,
         "TotalConfirmed": 279025,
         "NewDeaths": 18,
         "TotalDeaths": 9423,
         "NewRecovered": 1013,
         "TotalRecovered": 245706,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Ghana",
         "CountryCode": "GH",
         "Slug": "ghana",
         "NewConfirmed": 91,
         "TotalConfirmed": 46153,
         "NewDeaths": 2,
         "TotalDeaths": 299,
         "NewRecovered": 41,
         "TotalRecovered": 45299,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Greece",
         "CountryCode": "GR",
         "Slug": "greece",
         "NewConfirmed": 358,
         "TotalConfirmed": 16286,
         "NewDeaths": 5,
         "TotalDeaths": 357,
         "NewRecovered": 0,
         "TotalRecovered": 1347,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Grenada",
         "CountryCode": "GD",
         "Slug": "grenada",
         "NewConfirmed": 0,
         "TotalConfirmed": 24,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 24,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Guatemala",
         "CountryCode": "GT",
         "Slug": "guatemala",
         "NewConfirmed": 819,
         "TotalConfirmed": 87442,
         "NewDeaths": 17,
         "TotalDeaths": 3154,
         "NewRecovered": 590,
         "TotalRecovered": 76459,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Guinea",
         "CountryCode": "GN",
         "Slug": "guinea",
         "NewConfirmed": 47,
         "TotalConfirmed": 10434,
         "NewDeaths": 0,
         "TotalDeaths": 65,
         "NewRecovered": 21,
         "TotalRecovered": 9801,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Guinea-Bissau",
         "CountryCode": "GW",
         "Slug": "guinea-bissau",
         "NewConfirmed": 0,
         "TotalConfirmed": 2324,
         "NewDeaths": 0,
         "TotalDeaths": 39,
         "NewRecovered": 0,
         "TotalRecovered": 1549,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Guyana",
         "CountryCode": "GY",
         "Slug": "guyana",
         "NewConfirmed": 98,
         "TotalConfirmed": 2535,
         "NewDeaths": 2,
         "TotalDeaths": 69,
         "NewRecovered": 103,
         "TotalRecovered": 1464,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Haiti",
         "CountryCode": "HT",
         "Slug": "haiti",
         "NewConfirmed": 13,
         "TotalConfirmed": 8646,
         "NewDeaths": 2,
         "TotalDeaths": 225,
         "NewRecovered": 69,
         "TotalRecovered": 6551,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Holy See (Vatican City State)",
         "CountryCode": "VA",
         "Slug": "holy-see-vatican-city-state",
         "NewConfirmed": 0,
         "TotalConfirmed": 12,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 12,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Honduras",
         "CountryCode": "HN",
         "Slug": "honduras",
         "NewConfirmed": 369,
         "TotalConfirmed": 72675,
         "NewDeaths": 16,
         "TotalDeaths": 2222,
         "NewRecovered": 792,
         "TotalRecovered": 24022,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Hungary",
         "CountryCode": "HU",
         "Slug": "hungary",
         "NewConfirmed": 951,
         "TotalConfirmed": 20450,
         "NewDeaths": 8,
         "TotalDeaths": 702,
         "NewRecovered": 85,
         "TotalRecovered": 4644,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Iceland",
         "CountryCode": "IS",
         "Slug": "iceland",
         "NewConfirmed": 57,
         "TotalConfirmed": 2476,
         "NewDeaths": 0,
         "TotalDeaths": 10,
         "NewRecovered": 12,
         "TotalRecovered": 2142,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "India",
         "CountryCode": "IN",
         "Slug": "india",
         "NewConfirmed": 83347,
         "TotalConfirmed": 5646010,
         "NewDeaths": 1085,
         "TotalDeaths": 90020,
         "NewRecovered": 89746,
         "TotalRecovered": 4587613,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Indonesia",
         "CountryCode": "ID",
         "Slug": "indonesia",
         "NewConfirmed": 4465,
         "TotalConfirmed": 257388,
         "NewDeaths": 140,
         "TotalDeaths": 9977,
         "NewRecovered": 3660,
         "TotalRecovered": 187958,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Iran, Islamic Republic of",
         "CountryCode": "IR",
         "Slug": "iran",
         "NewConfirmed": 3605,
         "TotalConfirmed": 432798,
         "NewDeaths": 184,
         "TotalDeaths": 24840,
         "NewRecovered": 2109,
         "TotalRecovered": 365846,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Iraq",
         "CountryCode": "IQ",
         "Slug": "iraq",
         "NewConfirmed": 5055,
         "TotalConfirmed": 332635,
         "NewDeaths": 72,
         "TotalDeaths": 8754,
         "NewRecovered": 3231,
         "TotalRecovered": 264988,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Ireland",
         "CountryCode": "IE",
         "Slug": "ireland",
         "NewConfirmed": 231,
         "TotalConfirmed": 33675,
         "NewDeaths": 2,
         "TotalDeaths": 1794,
         "NewRecovered": 0,
         "TotalRecovered": 23364,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Israel",
         "CountryCode": "IL",
         "Slug": "israel",
         "NewConfirmed": 11316,
         "TotalConfirmed": 204690,
         "NewDeaths": 40,
         "TotalDeaths": 1325,
         "NewRecovered": 4212,
         "TotalRecovered": 144963,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Italy",
         "CountryCode": "IT",
         "Slug": "italy",
         "NewConfirmed": 1640,
         "TotalConfirmed": 302537,
         "NewDeaths": 20,
         "TotalDeaths": 35758,
         "NewRecovered": 995,
         "TotalRecovered": 220665,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Jamaica",
         "CountryCode": "JM",
         "Slug": "jamaica",
         "NewConfirmed": 125,
         "TotalConfirmed": 5395,
         "NewDeaths": 1,
         "TotalDeaths": 76,
         "NewRecovered": 0,
         "TotalRecovered": 1444,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Japan",
         "CountryCode": "JP",
         "Slug": "japan",
         "NewConfirmed": 236,
         "TotalConfirmed": 80009,
         "NewDeaths": 6,
         "TotalDeaths": 1525,
         "NewRecovered": 333,
         "TotalRecovered": 71547,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Jordan",
         "CountryCode": "JO",
         "Slug": "jordan",
         "NewConfirmed": 363,
         "TotalConfirmed": 6042,
         "NewDeaths": 2,
         "TotalDeaths": 35,
         "NewRecovered": 105,
         "TotalRecovered": 3812,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Kazakhstan",
         "CountryCode": "KZ",
         "Slug": "kazakhstan",
         "NewConfirmed": 79,
         "TotalConfirmed": 107529,
         "NewDeaths": 0,
         "TotalDeaths": 1699,
         "NewRecovered": 259,
         "TotalRecovered": 102323,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Kenya",
         "CountryCode": "KE",
         "Slug": "kenya",
         "NewConfirmed": 130,
         "TotalConfirmed": 37348,
         "NewDeaths": 5,
         "TotalDeaths": 664,
         "NewRecovered": 106,
         "TotalRecovered": 24253,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Korea (South)",
         "CountryCode": "KR",
         "Slug": "korea-south",
         "NewConfirmed": 125,
         "TotalConfirmed": 23341,
         "NewDeaths": 5,
         "TotalDeaths": 393,
         "NewRecovered": 182,
         "TotalRecovered": 20832,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Kuwait",
         "CountryCode": "KW",
         "Slug": "kuwait",
         "NewConfirmed": 616,
         "TotalConfirmed": 101299,
         "NewDeaths": 2,
         "TotalDeaths": 590,
         "NewRecovered": 729,
         "TotalRecovered": 92341,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Kyrgyzstan",
         "CountryCode": "KG",
         "Slug": "kyrgyzstan",
         "NewConfirmed": 88,
         "TotalConfirmed": 45630,
         "NewDeaths": 0,
         "TotalDeaths": 1063,
         "NewRecovered": 108,
         "TotalRecovered": 41904,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Lao PDR",
         "CountryCode": "LA",
         "Slug": "lao-pdr",
         "NewConfirmed": 0,
         "TotalConfirmed": 23,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 22,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Latvia",
         "CountryCode": "LV",
         "Slug": "latvia",
         "NewConfirmed": 12,
         "TotalConfirmed": 1572,
         "NewDeaths": 0,
         "TotalDeaths": 36,
         "NewRecovered": 0,
         "TotalRecovered": 1248,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Lebanon",
         "CountryCode": "LB",
         "Slug": "lebanon",
         "NewConfirmed": 940,
         "TotalConfirmed": 31792,
         "NewDeaths": 13,
         "TotalDeaths": 328,
         "NewRecovered": 649,
         "TotalRecovered": 13527,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Lesotho",
         "CountryCode": "LS",
         "Slug": "lesotho",
         "NewConfirmed": 83,
         "TotalConfirmed": 1507,
         "NewDeaths": 2,
         "TotalDeaths": 35,
         "NewRecovered": 12,
         "TotalRecovered": 766,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Liberia",
         "CountryCode": "LR",
         "Slug": "liberia",
         "NewConfirmed": 1,
         "TotalConfirmed": 1337,
         "NewDeaths": 0,
         "TotalDeaths": 82,
         "NewRecovered": 1,
         "TotalRecovered": 1219,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Libya",
         "CountryCode": "LY",
         "Slug": "libya",
         "NewConfirmed": 651,
         "TotalConfirmed": 30097,
         "NewDeaths": 9,
         "TotalDeaths": 469,
         "NewRecovered": 517,
         "TotalRecovered": 16430,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Liechtenstein",
         "CountryCode": "LI",
         "Slug": "liechtenstein",
         "NewConfirmed": 1,
         "TotalConfirmed": 116,
         "NewDeaths": 0,
         "TotalDeaths": 1,
         "NewRecovered": 0,
         "TotalRecovered": 110,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Lithuania",
         "CountryCode": "LT",
         "Slug": "lithuania",
         "NewConfirmed": 73,
         "TotalConfirmed": 3932,
         "NewDeaths": 0,
         "TotalDeaths": 87,
         "NewRecovered": 21,
         "TotalRecovered": 2246,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Luxembourg",
         "CountryCode": "LU",
         "Slug": "luxembourg",
         "NewConfirmed": 74,
         "TotalConfirmed": 8090,
         "NewDeaths": 0,
         "TotalDeaths": 124,
         "NewRecovered": 14,
         "TotalRecovered": 6862,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Macao, SAR China",
         "CountryCode": "MO",
         "Slug": "macao-sar-china",
         "NewConfirmed": 0,
         "TotalConfirmed": 0,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 0,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Macedonia, Republic of",
         "CountryCode": "MK",
         "Slug": "macedonia",
         "NewConfirmed": 182,
         "TotalConfirmed": 17049,
         "NewDeaths": 5,
         "TotalDeaths": 710,
         "NewRecovered": 102,
         "TotalRecovered": 14186,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Madagascar",
         "CountryCode": "MG",
         "Slug": "madagascar",
         "NewConfirmed": 31,
         "TotalConfirmed": 16167,
         "NewDeaths": 0,
         "TotalDeaths": 226,
         "NewRecovered": 45,
         "TotalRecovered": 14788,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Malawi",
         "CountryCode": "MW",
         "Slug": "malawi",
         "NewConfirmed": 7,
         "TotalConfirmed": 5746,
         "NewDeaths": 0,
         "TotalDeaths": 179,
         "NewRecovered": 75,
         "TotalRecovered": 4140,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Malaysia",
         "CountryCode": "MY",
         "Slug": "malaysia",
         "NewConfirmed": 147,
         "TotalConfirmed": 10505,
         "NewDeaths": 3,
         "TotalDeaths": 133,
         "NewRecovered": 39,
         "TotalRecovered": 9602,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Maldives",
         "CountryCode": "MV",
         "Slug": "maldives",
         "NewConfirmed": 67,
         "TotalConfirmed": 9885,
         "NewDeaths": 0,
         "TotalDeaths": 34,
         "NewRecovered": 92,
         "TotalRecovered": 8530,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Mali",
         "CountryCode": "ML",
         "Slug": "mali",
         "NewConfirmed": 4,
         "TotalConfirmed": 3034,
         "NewDeaths": 1,
         "TotalDeaths": 130,
         "NewRecovered": 2,
         "TotalRecovered": 2382,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Malta",
         "CountryCode": "MT",
         "Slug": "malta",
         "NewConfirmed": 42,
         "TotalConfirmed": 2856,
         "NewDeaths": 2,
         "TotalDeaths": 25,
         "NewRecovered": 60,
         "TotalRecovered": 2173,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Mauritania",
         "CountryCode": "MR",
         "Slug": "mauritania",
         "NewConfirmed": 22,
         "TotalConfirmed": 7425,
         "NewDeaths": 0,
         "TotalDeaths": 161,
         "NewRecovered": 17,
         "TotalRecovered": 7028,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Mauritius",
         "CountryCode": "MU",
         "Slug": "mauritius",
         "NewConfirmed": 0,
         "TotalConfirmed": 367,
         "NewDeaths": 0,
         "TotalDeaths": 10,
         "NewRecovered": 0,
         "TotalRecovered": 339,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Mexico",
         "CountryCode": "MX",
         "Slug": "mexico",
         "NewConfirmed": 4786,
         "TotalConfirmed": 710049,
         "NewDeaths": 601,
         "TotalDeaths": 74949,
         "NewRecovered": 2658,
         "TotalRecovered": 601611,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Moldova",
         "CountryCode": "MD",
         "Slug": "moldova",
         "NewConfirmed": 786,
         "TotalConfirmed": 48232,
         "NewDeaths": 14,
         "TotalDeaths": 1244,
         "NewRecovered": 529,
         "TotalRecovered": 36071,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Monaco",
         "CountryCode": "MC",
         "Slug": "monaco",
         "NewConfirmed": 2,
         "TotalConfirmed": 199,
         "NewDeaths": 0,
         "TotalDeaths": 1,
         "NewRecovered": 2,
         "TotalRecovered": 165,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Mongolia",
         "CountryCode": "MN",
         "Slug": "mongolia",
         "NewConfirmed": 0,
         "TotalConfirmed": 313,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 302,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Montenegro",
         "CountryCode": "ME",
         "Slug": "montenegro",
         "NewConfirmed": 290,
         "TotalConfirmed": 9428,
         "NewDeaths": 5,
         "TotalDeaths": 151,
         "NewRecovered": 184,
         "TotalRecovered": 5728,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Morocco",
         "CountryCode": "MA",
         "Slug": "morocco",
         "NewConfirmed": 2397,
         "TotalConfirmed": 107743,
         "NewDeaths": 29,
         "TotalDeaths": 1918,
         "NewRecovered": 2361,
         "TotalRecovered": 88244,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Mozambique",
         "CountryCode": "MZ",
         "Slug": "mozambique",
         "NewConfirmed": 148,
         "TotalConfirmed": 7262,
         "NewDeaths": 4,
         "TotalDeaths": 49,
         "NewRecovered": 286,
         "TotalRecovered": 4350,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Myanmar",
         "CountryCode": "MM",
         "Slug": "myanmar",
         "NewConfirmed": 868,
         "TotalConfirmed": 7827,
         "NewDeaths": 17,
         "TotalDeaths": 133,
         "NewRecovered": 134,
         "TotalRecovered": 2085,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Namibia",
         "CountryCode": "NA",
         "Slug": "namibia",
         "NewConfirmed": 56,
         "TotalConfirmed": 10663,
         "NewDeaths": 1,
         "TotalDeaths": 117,
         "NewRecovered": 72,
         "TotalRecovered": 8431,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Nepal",
         "CountryCode": "NP",
         "Slug": "nepal",
         "NewConfirmed": 1172,
         "TotalConfirmed": 67804,
         "NewDeaths": 7,
         "TotalDeaths": 436,
         "NewRecovered": 1893,
         "TotalRecovered": 49954,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Netherlands",
         "CountryCode": "NL",
         "Slug": "netherlands",
         "NewConfirmed": 2357,
         "TotalConfirmed": 100597,
         "NewDeaths": 5,
         "TotalDeaths": 6296,
         "NewRecovered": 0,
         "TotalRecovered": 0,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "New Zealand",
         "CountryCode": "NZ",
         "Slug": "new-zealand",
         "NewConfirmed": 3,
         "TotalConfirmed": 1827,
         "NewDeaths": 0,
         "TotalDeaths": 25,
         "NewRecovered": 0,
         "TotalRecovered": 1737,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Nicaragua",
         "CountryCode": "NI",
         "Slug": "nicaragua",
         "NewConfirmed": 0,
         "TotalConfirmed": 5073,
         "NewDeaths": 0,
         "TotalDeaths": 149,
         "NewRecovered": 0,
         "TotalRecovered": 2913,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Niger",
         "CountryCode": "NE",
         "Slug": "niger",
         "NewConfirmed": 0,
         "TotalConfirmed": 1193,
         "NewDeaths": 0,
         "TotalDeaths": 69,
         "NewRecovered": 3,
         "TotalRecovered": 1107,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Nigeria",
         "CountryCode": "NG",
         "Slug": "nigeria",
         "NewConfirmed": 111,
         "TotalConfirmed": 57724,
         "NewDeaths": 2,
         "TotalDeaths": 1102,
         "NewRecovered": 149,
         "TotalRecovered": 48985,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Norway",
         "CountryCode": "NO",
         "Slug": "norway",
         "NewConfirmed": 124,
         "TotalConfirmed": 13277,
         "NewDeaths": 0,
         "TotalDeaths": 267,
         "NewRecovered": 0,
         "TotalRecovered": 10371,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Oman",
         "CountryCode": "OM",
         "Slug": "oman",
         "NewConfirmed": 628,
         "TotalConfirmed": 95339,
         "NewDeaths": 10,
         "TotalDeaths": 875,
         "NewRecovered": 287,
         "TotalRecovered": 86482,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Pakistan",
         "CountryCode": "PK",
         "Slug": "pakistan",
         "NewConfirmed": 799,
         "TotalConfirmed": 308217,
         "NewDeaths": 5,
         "TotalDeaths": 6437,
         "NewRecovered": 476,
         "TotalRecovered": 294392,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Palestinian Territory",
         "CountryCode": "PS",
         "Slug": "palestine",
         "NewConfirmed": 503,
         "TotalConfirmed": 37083,
         "NewDeaths": 3,
         "TotalDeaths": 272,
         "NewRecovered": 819,
         "TotalRecovered": 26288,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Panama",
         "CountryCode": "PA",
         "Slug": "panama",
         "NewConfirmed": 706,
         "TotalConfirmed": 107990,
         "NewDeaths": 6,
         "TotalDeaths": 2291,
         "NewRecovered": 1119,
         "TotalRecovered": 84437,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Papua New Guinea",
         "CountryCode": "PG",
         "Slug": "papua-new-guinea",
         "NewConfirmed": 0,
         "TotalConfirmed": 527,
         "NewDeaths": 0,
         "TotalDeaths": 7,
         "NewRecovered": 0,
         "TotalRecovered": 232,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Paraguay",
         "CountryCode": "PY",
         "Slug": "paraguay",
         "NewConfirmed": 743,
         "TotalConfirmed": 35571,
         "NewDeaths": 22,
         "TotalDeaths": 727,
         "NewRecovered": 610,
         "TotalRecovered": 19867,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Peru",
         "CountryCode": "PE",
         "Slug": "peru",
         "NewConfirmed": 7651,
         "TotalConfirmed": 776546,
         "NewDeaths": 199,
         "TotalDeaths": 31568,
         "NewRecovered": 28652,
         "TotalRecovered": 636489,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Philippines",
         "CountryCode": "PH",
         "Slug": "philippines",
         "NewConfirmed": 2802,
         "TotalConfirmed": 294591,
         "NewDeaths": 42,
         "TotalDeaths": 5091,
         "NewRecovered": 730,
         "TotalRecovered": 231373,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Poland",
         "CountryCode": "PL",
         "Slug": "poland",
         "NewConfirmed": 974,
         "TotalConfirmed": 81673,
         "NewDeaths": 28,
         "TotalDeaths": 2344,
         "NewRecovered": 589,
         "TotalRecovered": 65561,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Portugal",
         "CountryCode": "PT",
         "Slug": "portugal",
         "NewConfirmed": 802,
         "TotalConfirmed": 70465,
         "NewDeaths": 3,
         "TotalDeaths": 1928,
         "NewRecovered": 316,
         "TotalRecovered": 46290,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Qatar",
         "CountryCode": "QA",
         "Slug": "qatar",
         "NewConfirmed": 258,
         "TotalConfirmed": 124175,
         "NewDeaths": 1,
         "TotalDeaths": 212,
         "NewRecovered": 240,
         "TotalRecovered": 121006,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Republic of Kosovo",
         "CountryCode": "XK",
         "Slug": "kosovo",
         "NewConfirmed": 0,
         "TotalConfirmed": 12683,
         "NewDeaths": 0,
         "TotalDeaths": 488,
         "NewRecovered": 0,
         "TotalRecovered": 8788,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Romania",
         "CountryCode": "RO",
         "Slug": "romania",
         "NewConfirmed": 1767,
         "TotalConfirmed": 116415,
         "NewDeaths": 47,
         "TotalDeaths": 4550,
         "NewRecovered": 1389,
         "TotalRecovered": 93558,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Russian Federation",
         "CountryCode": "RU",
         "Slug": "russia",
         "NewConfirmed": 6330,
         "TotalConfirmed": 1117487,
         "NewDeaths": 145,
         "TotalDeaths": 19720,
         "NewRecovered": 5679,
         "TotalRecovered": 920602,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Rwanda",
         "CountryCode": "RW",
         "Slug": "rwanda",
         "NewConfirmed": 41,
         "TotalConfirmed": 4779,
         "NewDeaths": 0,
         "TotalDeaths": 27,
         "NewRecovered": 4,
         "TotalRecovered": 2995,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Réunion",
         "CountryCode": "RE",
         "Slug": "réunion",
         "NewConfirmed": 0,
         "TotalConfirmed": 0,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 0,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Saint Kitts and Nevis",
         "CountryCode": "KN",
         "Slug": "saint-kitts-and-nevis",
         "NewConfirmed": 0,
         "TotalConfirmed": 19,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 17,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Saint Lucia",
         "CountryCode": "LC",
         "Slug": "saint-lucia",
         "NewConfirmed": 0,
         "TotalConfirmed": 27,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 26,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Saint Vincent and Grenadines",
         "CountryCode": "VC",
         "Slug": "saint-vincent-and-the-grenadines",
         "NewConfirmed": 0,
         "TotalConfirmed": 64,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 64,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "San Marino",
         "CountryCode": "SM",
         "Slug": "san-marino",
         "NewConfirmed": 0,
         "TotalConfirmed": 723,
         "NewDeaths": 0,
         "TotalDeaths": 42,
         "NewRecovered": 0,
         "TotalRecovered": 669,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Sao Tome and Principe",
         "CountryCode": "ST",
         "Slug": "sao-tome-and-principe",
         "NewConfirmed": 0,
         "TotalConfirmed": 908,
         "NewDeaths": 0,
         "TotalDeaths": 15,
         "NewRecovered": 0,
         "TotalRecovered": 880,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Saudi Arabia",
         "CountryCode": "SA",
         "Slug": "saudi-arabia",
         "NewConfirmed": 561,
         "TotalConfirmed": 331359,
         "NewDeaths": 27,
         "TotalDeaths": 4569,
         "NewRecovered": 1102,
         "TotalRecovered": 313786,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Senegal",
         "CountryCode": "SN",
         "Slug": "senegal",
         "NewConfirmed": 36,
         "TotalConfirmed": 14795,
         "NewDeaths": 1,
         "TotalDeaths": 303,
         "NewRecovered": 97,
         "TotalRecovered": 11718,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Serbia",
         "CountryCode": "RS",
         "Slug": "serbia",
         "NewConfirmed": 81,
         "TotalConfirmed": 33080,
         "NewDeaths": 1,
         "TotalDeaths": 744,
         "NewRecovered": 0,
         "TotalRecovered": 0,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Seychelles",
         "CountryCode": "SC",
         "Slug": "seychelles",
         "NewConfirmed": 0,
         "TotalConfirmed": 143,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 136,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Sierra Leone",
         "CountryCode": "SL",
         "Slug": "sierra-leone",
         "NewConfirmed": 9,
         "TotalConfirmed": 2183,
         "NewDeaths": 0,
         "TotalDeaths": 72,
         "NewRecovered": 13,
         "TotalRecovered": 1665,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Singapore",
         "CountryCode": "SG",
         "Slug": "singapore",
         "NewConfirmed": 12,
         "TotalConfirmed": 57639,
         "NewDeaths": 0,
         "TotalDeaths": 27,
         "NewRecovered": 29,
         "TotalRecovered": 57291,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Slovakia",
         "CountryCode": "SK",
         "Slug": "slovakia",
         "NewConfirmed": 338,
         "TotalConfirmed": 7269,
         "NewDeaths": 1,
         "TotalDeaths": 41,
         "NewRecovered": 220,
         "TotalRecovered": 3888,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Slovenia",
         "CountryCode": "SI",
         "Slug": "slovenia",
         "NewConfirmed": 136,
         "TotalConfirmed": 4694,
         "NewDeaths": 1,
         "TotalDeaths": 143,
         "NewRecovered": 120,
         "TotalRecovered": 3168,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Somalia",
         "CountryCode": "SO",
         "Slug": "somalia",
         "NewConfirmed": 0,
         "TotalConfirmed": 3465,
         "NewDeaths": 0,
         "TotalDeaths": 98,
         "NewRecovered": 0,
         "TotalRecovered": 2877,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "South Africa",
         "CountryCode": "ZA",
         "Slug": "south-africa",
         "NewConfirmed": 1906,
         "TotalConfirmed": 665188,
         "NewDeaths": 88,
         "TotalDeaths": 16206,
         "NewRecovered": 1325,
         "TotalRecovered": 594229,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "South Sudan",
         "CountryCode": "SS",
         "Slug": "south-sudan",
         "NewConfirmed": 4,
         "TotalConfirmed": 2664,
         "NewDeaths": 0,
         "TotalDeaths": 49,
         "NewRecovered": 0,
         "TotalRecovered": 1290,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Spain",
         "CountryCode": "ES",
         "Slug": "spain",
         "NewConfirmed": 11289,
         "TotalConfirmed": 693556,
         "NewDeaths": 130,
         "TotalDeaths": 31034,
         "NewRecovered": 0,
         "TotalRecovered": 150376,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Sri Lanka",
         "CountryCode": "LK",
         "Slug": "sri-lanka",
         "NewConfirmed": 11,
         "TotalConfirmed": 3324,
         "NewDeaths": 0,
         "TotalDeaths": 13,
         "NewRecovered": 11,
         "TotalRecovered": 3129,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Sudan",
         "CountryCode": "SD",
         "Slug": "sudan",
         "NewConfirmed": 0,
         "TotalConfirmed": 13578,
         "NewDeaths": 0,
         "TotalDeaths": 836,
         "NewRecovered": 0,
         "TotalRecovered": 6760,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Suriname",
         "CountryCode": "SR",
         "Slug": "suriname",
         "NewConfirmed": 20,
         "TotalConfirmed": 4779,
         "NewDeaths": 1,
         "TotalDeaths": 101,
         "NewRecovered": 19,
         "TotalRecovered": 4560,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Swaziland",
         "CountryCode": "SZ",
         "Slug": "swaziland",
         "NewConfirmed": 36,
         "TotalConfirmed": 5343,
         "NewDeaths": 2,
         "TotalDeaths": 108,
         "NewRecovered": 21,
         "TotalRecovered": 4693,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Sweden",
         "CountryCode": "SE",
         "Slug": "sweden",
         "NewConfirmed": 320,
         "TotalConfirmed": 89756,
         "NewDeaths": 6,
         "TotalDeaths": 5876,
         "NewRecovered": 0,
         "TotalRecovered": 0,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Switzerland",
         "CountryCode": "CH",
         "Slug": "switzerland",
         "NewConfirmed": 437,
         "TotalConfirmed": 51101,
         "NewDeaths": 6,
         "TotalDeaths": 2060,
         "NewRecovered": 0,
         "TotalRecovered": 42100,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Syrian Arab Republic (Syria)",
         "CountryCode": "SY",
         "Slug": "syria",
         "NewConfirmed": 47,
         "TotalConfirmed": 3924,
         "NewDeaths": 3,
         "TotalDeaths": 181,
         "NewRecovered": 15,
         "TotalRecovered": 998,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Taiwan, Republic of China",
         "CountryCode": "TW",
         "Slug": "taiwan",
         "NewConfirmed": 0,
         "TotalConfirmed": 509,
         "NewDeaths": 0,
         "TotalDeaths": 7,
         "NewRecovered": 1,
         "TotalRecovered": 480,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Tajikistan",
         "CountryCode": "TJ",
         "Slug": "tajikistan",
         "NewConfirmed": 43,
         "TotalConfirmed": 9475,
         "NewDeaths": 1,
         "TotalDeaths": 74,
         "NewRecovered": 45,
         "TotalRecovered": 8244,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Tanzania, United Republic of",
         "CountryCode": "TZ",
         "Slug": "tanzania",
         "NewConfirmed": 0,
         "TotalConfirmed": 509,
         "NewDeaths": 0,
         "TotalDeaths": 21,
         "NewRecovered": 0,
         "TotalRecovered": 183,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Thailand",
         "CountryCode": "TH",
         "Slug": "thailand",
         "NewConfirmed": 2,
         "TotalConfirmed": 3516,
         "NewDeaths": 0,
         "TotalDeaths": 59,
         "NewRecovered": 8,
         "TotalRecovered": 3353,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Timor-Leste",
         "CountryCode": "TL",
         "Slug": "timor-leste",
         "NewConfirmed": 0,
         "TotalConfirmed": 27,
         "NewDeaths": 0,
         "TotalDeaths": 0,
         "NewRecovered": 0,
         "TotalRecovered": 27,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Togo",
         "CountryCode": "TG",
         "Slug": "togo",
         "NewConfirmed": 18,
         "TotalConfirmed": 1701,
         "NewDeaths": 0,
         "TotalDeaths": 41,
         "NewRecovered": 7,
         "TotalRecovered": 1297,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Trinidad and Tobago",
         "CountryCode": "TT",
         "Slug": "trinidad-and-tobago",
         "NewConfirmed": 110,
         "TotalConfirmed": 4136,
         "NewDeaths": 2,
         "TotalDeaths": 67,
         "NewRecovered": 89,
         "TotalRecovered": 1960,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Tunisia",
         "CountryCode": "TN",
         "Slug": "tunisia",
         "NewConfirmed": 1219,
         "TotalConfirmed": 12479,
         "NewDeaths": 10,
         "TotalDeaths": 174,
         "NewRecovered": 0,
         "TotalRecovered": 2386,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Turkey",
         "CountryCode": "TR",
         "Slug": "turkey",
         "NewConfirmed": 1767,
         "TotalConfirmed": 308069,
         "NewDeaths": 72,
         "TotalDeaths": 7711,
         "NewRecovered": 1027,
         "TotalRecovered": 270723,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Uganda",
         "CountryCode": "UG",
         "Slug": "uganda",
         "NewConfirmed": 167,
         "TotalConfirmed": 6879,
         "NewDeaths": 5,
         "TotalDeaths": 69,
         "NewRecovered": 183,
         "TotalRecovered": 2961,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Ukraine",
         "CountryCode": "UA",
         "Slug": "ukraine",
         "NewConfirmed": 3598,
         "TotalConfirmed": 189488,
         "NewDeaths": 68,
         "TotalDeaths": 3784,
         "NewRecovered": 1840,
         "TotalRecovered": 84767,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "United Arab Emirates",
         "CountryCode": "AE",
         "Slug": "united-arab-emirates",
         "NewConfirmed": 1083,
         "TotalConfirmed": 87530,
         "NewDeaths": 1,
         "TotalDeaths": 406,
         "NewRecovered": 970,
         "TotalRecovered": 76995,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "United Kingdom",
         "CountryCode": "GB",
         "Slug": "united-kingdom",
         "NewConfirmed": 6187,
         "TotalConfirmed": 412245,
         "NewDeaths": 37,
         "TotalDeaths": 41951,
         "NewRecovered": 9,
         "TotalRecovered": 2247,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "United States of America",
         "CountryCode": "US",
         "Slug": "united-states",
         "NewConfirmed": 37330,
         "TotalConfirmed": 6933548,
         "NewDeaths": 1098,
         "TotalDeaths": 201884,
         "NewRecovered": 23297,
         "TotalRecovered": 2670256,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Uruguay",
         "CountryCode": "UY",
         "Slug": "uruguay",
         "NewConfirmed": 12,
         "TotalConfirmed": 1946,
         "NewDeaths": 1,
         "TotalDeaths": 47,
         "NewRecovered": 16,
         "TotalRecovered": 1661,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Uzbekistan",
         "CountryCode": "UZ",
         "Slug": "uzbekistan",
         "NewConfirmed": 590,
         "TotalConfirmed": 53275,
         "NewDeaths": 2,
         "TotalDeaths": 444,
         "NewRecovered": 582,
         "TotalRecovered": 49649,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Venezuela (Bolivarian Republic)",
         "CountryCode": "VE",
         "Slug": "venezuela",
         "NewConfirmed": 986,
         "TotalConfirmed": 69439,
         "NewDeaths": 10,
         "TotalDeaths": 574,
         "NewRecovered": 985,
         "TotalRecovered": 58759,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Viet Nam",
         "CountryCode": "VN",
         "Slug": "vietnam",
         "NewConfirmed": 1,
         "TotalConfirmed": 1069,
         "NewDeaths": 0,
         "TotalDeaths": 35,
         "NewRecovered": 34,
         "TotalRecovered": 991,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Western Sahara",
         "CountryCode": "EH",
         "Slug": "western-sahara",
         "NewConfirmed": 0,
         "TotalConfirmed": 10,
         "NewDeaths": 0,
         "TotalDeaths": 1,
         "NewRecovered": 0,
         "TotalRecovered": 8,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Yemen",
         "CountryCode": "YE",
         "Slug": "yemen",
         "NewConfirmed": 1,
         "TotalConfirmed": 2029,
         "NewDeaths": 0,
         "TotalDeaths": 586,
         "NewRecovered": 5,
         "TotalRecovered": 1245,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Zambia",
         "CountryCode": "ZM",
         "Slug": "zambia",
         "NewConfirmed": 54,
         "TotalConfirmed": 14443,
         "NewDeaths": 1,
         "TotalDeaths": 332,
         "NewRecovered": 0,
         "TotalRecovered": 13629,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      },
      {
         "Country": "Zimbabwe",
         "CountryCode": "ZW",
         "Slug": "zimbabwe",
         "NewConfirmed": 14,
         "TotalConfirmed": 7725,
         "NewDeaths": 1,
         "TotalDeaths": 227,
         "NewRecovered": 28,
         "TotalRecovered": 6007,
         "Date": "2020-09-24T14:21:20Z",
         "Premium": {}
      }
   ],
   "Date": "2020-09-24T14:21:20Z"
}


module.exports = countries;
